remote_theme: pages-themes/slate@v0.2.0
plugins:
  - jekyll-remote-theme

title: UnitSocializer
description: Simplify your sociable tests with minimal effort!
show_downloads: false
sass:
  style: compressed